version: '3.4'

services:
  postgres:
    image: postgres:12.8
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=link_bush
      - POSTGRES_PASSWORD=link_bush
  redis:
    image: redis:latest
    ports:
      - 63791:6379